version: "3.1"

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: $PGPASSWORD
            POSTGRES_USER: $PGUSER
            POSTGRES_DB: $DATABASE
        ports:
            - 5432:5432
        networks:
            - botnet

    slackbot:
        container_name: bot
        build:
            context: .
        command: python run.py
        restart: always
        networks:
            - botnet
        env_file:
            - ".env"
        depends_on:
            - db


networks:
    botnet:
        driver: bridge
